Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2019
Var
// Seção de Declarações das variáveis 
j: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para j de 1 ate 10 faca:
  escreval(j)
  Fimpara

Fimalgoritmo